export const pokemonApiTypes = {
  GET_POKEMONS: '@API/GET_POKEMONS',
  GET_NEXT_POKEMONS: '@API/GET_NEXT_POKEMONS',
  GET_THIRD_PAGE_POKEMONS: '@API/GET_THIRD_PAGE_POKEMONS',
  ADD_POKEMONS: '@API/ADD_POKEMONS',
};
